### ISSUE TITLE
Garbage in https://api.nostr.watch/v1/offline

### ISSUE THREAD

**Issue by gourcetools** [dskvr/nostr-watch#285]
![image](https://user-images.githubusercontent.com/120996278/216313403-86a39a2e-1c75-4f70-bf88-adec261ce653.png)

I guess you get that data from nostr? 
"recommend" event kinds? 
... people publish garbage with event kind... i've been thinking this is a issue before... it's good when used properly but it's not the case...

```
wss://%20nostr-pub.wellorder.net
wss://nostr.dress.io
wss://npub1kx6hgrullazc3nq7ka6jphv3uru5jspqs5t2kdrkh60gtk3razpsn23fu9
wss://damus！又来一个新事物

npub15tqd4r697cjkmfcsqlrxhs8klqx5s5tm4cdq0q8xx3yxvj42cs0qps7czr
wss://https://okx.com/join/1858500
wss://https://www.huobi.com.bo/zh-cn/v/register/double-invite/?invite_code=462s6223&inviter_id=462s6223
wss://accounts.binance.me/zh-cn/register?ref=62709106
①okx交易所
https://www.aogcdg.com/join/1858500
②币安交易所
https://accounts.binance.com/zh-cn/register?ref=62709106
邀请码62709106
③gate交易所
https://www.gate.ac/signup/11987778

④币赢交易所
https://www.coinw.fan/front/register?r=1804287&language=zh_cn
推荐码1804287

㈡港美股交易所
以下两个券商用同一个交易软件
①wbroker港美股券商支持加密数字货币入金，出金

https://p.wbroker.info/unhmb5t?lan=zh

推荐码wvkmjpv
②华通证券国际，支持各国银行

https://p.infastbr.com/cezexn0?lan=zh

推荐码7tyd
wss://https://www.gate.ac/signup/11987778
wss://https://accounts.binance.me/zh-cn/https://www.gate.ac/signup/11987778register?ref=62709106
```

**Comment by dskvr** [comment]
Hey! Yes, this is true. Was hoping nobody would notice ;) 

It's actually using contact lists(kind 3), kind 2 is barely used. 

Unfortunately, I do not have the time or bandwidth to deal with it rn. And additionally, it's not that big of a deal to sanitize it, been rummaging through garbage for months, but have bigger fish to try. 

Will address it in a week or so, thanks for the report.

**Comment by dskvr** [comment]
So some further thoughts on this...

1. What are the potential use cases of `/v1/offline`? In reality, the best use case I can think of is searching an array for a specific relay to see if it's considered offline. Which could also be achieved with `/v1/online` 
2. "garbage" is subjective, as long as it starts with `wss://` then it could be a relay.
  - This could be mitigated by assuring that the "relay" was "online" at some point, though, this also isn't perfect, as a relay can be easily faked. 
3. There actually shouldn't be anything that starts with `https://` in there, so that is a bug that I need to look into.

**Comment by gourcetools** [comment]
Hey, there is no hurry, i just want to make stats by day. I know it's silly... no hurry this is really not important as of now...

**Comment by dskvr** [comment]
It's really not too big of a deal for me, because the API runs off the same daemon as the Nostr API, which I am currently working on. I didn't test it, but I did just deploy the changes, you should see less garbage now, let me know if you don't.
